backend:
  image: devops108/backend_repo:latest
  port: 8000
  replicas: 1

frontend:
  image: devops108/frontend_repo:latest
  port: 80
  replicas: 1

service:
  frontend:
    type: NodePort
  backend:
    type: ClusterIP

prometheus:
  scrape: true   # we will add annotations for scrape