apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-chart.fullname" . }}-backend-svc
  labels:
    app: {{ include "app-chart.name" . }}
    component: backend
spec:
  type: {{ .Values.service.backend.type | default "ClusterIP" }}
  selector:
    app: {{ include "app-chart.name" . }}
    component: backend
  ports:
  - port: {{ .Values.backend.port }}
    targetPort: {{ .Values.backend.port }}
    name: http
