apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-servicemonitor
  namespace: monitoring
  labels:
    release: prometheus    # must match your Prometheus release name
spec:
  selector:
    matchLabels:
      app: app-chart
      component: backend
  namespaceSelector:
    matchNames:
    - app-poc
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
